import { IrregularInboundFlight } from "../../models/irregular-inbound-flight.model";

export const MOCK_IRREGULAR_INBOUND: IrregularInboundFlight = {
  flightinfo: [
    {
      flightNo: 'CI123',
      arrivalPort: '台北',
      departurePort: '東京成田',
      gate: 'A12',
      sta: '08:30',
      ata: '09:10',
      delay: '40',
      status: '延誤/有異常',
      reason: '天候不佳',
      handle: '已通知旅客',
    },
    {
      flightNo: 'BR807',
      arrivalPort: '台北',
      departurePort: '香港',
      gate: 'B5',
      sta: '10:00',
      ata: '10:45',
      delay: '105',
      status: '延誤/有異常',
      reason: '機務檢修',
      handle: '安排餐點',
    },
    {
      flightNo: 'JL809',
      arrivalPort: '台北',
      departurePort: '大阪關西',
      gate: 'C3',
      sta: '11:20',
      ata: '11:20',
      delay: '0',
      status: '已到達',
      reason: '—',
      handle: '正常作業',
    },
       {
      flightNo: 'CI123',
      arrivalPort: '台北',
      departurePort: '東京成田',
      gate: 'A12',
      sta: '08:30',
      ata: '09:10',
      delay: '40',
      status: '延誤/有異常/有異常',
      reason: '天候不佳',
      handle: '已通知旅客',
    },
    {
      flightNo: 'BR807',
      arrivalPort: '台北',
      departurePort: '香港',
      gate: 'B5',
      sta: '10:00',
      ata: '10:45',
      delay: '105',
      status: '延誤/有異常',
      reason: '機務檢修',
      handle: '安排餐點',
    },
    {
      flightNo: 'JL809',
      arrivalPort: '台北',
      departurePort: '大阪關西',
      gate: 'C3',
      sta: '11:20',
      ata: '11:20',
      delay: '0',
      status: '已到達',
      reason: '—',
      handle: '正常作業',
    },
       {
      flightNo: 'CI123',
      arrivalPort: '台北',
      departurePort: '東京成田',
      gate: 'A12',
      sta: '08:30',
      ata: '09:10',
      delay: '40',
      status: '延誤/有異常',
      reason: '天候不佳',
      handle: '已通知旅客',
    },
    {
      flightNo: 'BR807',
      arrivalPort: '台北',
      departurePort: '香港',
      gate: 'B5',
      sta: '10:00',
      ata: '10:45',
      delay: '105',
      status: '延誤/有異常',
      reason: '機務檢修',
      handle: '安排餐點',
    },
    {
      flightNo: 'JL809',
      arrivalPort: '台北',
      departurePort: '大阪關西',
      gate: 'C3',
      sta: '11:20',
      ata: '11:20',
      delay: '0',
      status: '已到達',
      reason: '—',
      handle: '正常作業',
    },
  ],
  actualFlight: 3,
  actualPax: 420,
  estFlight: 4,
  estPax: 560,
};
